-- Insert categories
INSERT INTO categories (title, created_at, updated_at) VALUES
    ('Property', NOW(), NOW()),
    ('Power Management', NOW(), NOW()),
    ('Logam Mulia', NOW(), NOW()),
    ('Perlengkapan Pesta & Craft', NOW(), NOW()),
    ('Komputer & Laptop', NOW(), NOW()),
    ('Fashion Pria', NOW(), NOW()),
    ('Handphone & Tablet', NOW(), NOW()),
    ('Film & Musik', NOW(), NOW()),
    ('Dapur', NOW(), NOW()),
    ('Security Camera', NOW(), NOW()),
    ('Buku', NOW(), NOW()),
    ('Fashion Anak & Bayi', NOW(), NOW()),
    ('Otomotif', NOW(), NOW()),
    ('Perawatan Tubuh', NOW(), NOW()),
    ('Kecantikan', NOW(), NOW()),
    ('Gaming', NOW(), NOW()),
    ('Mainan & Hobi', NOW(), NOW()),
    ('Jasa', NOW(), NOW()),
    ('Access Control', NOW(), NOW()),
    ('Kendaraan', NOW(), NOW()),
    ('Display', NOW(), NOW()),
    ('Ibu & Bayi', NOW(), NOW()),
    ('Olahraga', NOW(), NOW()),
    ('Kesehatan', NOW(), NOW()),
    ('Office & Stationery', NOW(), NOW()),
    ('Kiosk', NOW(), NOW()),
    ('Fashion Muslim', NOW(), NOW()),
    ('Pertukangan', NOW(), NOW()),
    ('Audio & Kamera', NOW(), NOW()),
    ('Elektronik', NOW(), NOW()),
    ('Sensors', NOW(), NOW()),
    ('Lighting', NOW(), NOW()),
    ('Fashion Wanita', NOW(), NOW()),
    ('Rumah Tangga', NOW(), NOW());
