export enum ENV_VARIABLES {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
}

export enum NODE_ENV {
  DEVELOPMENT = 'development',
  PROUCTION = 'production',
}
